// reference.js
// Exposes school data on the global window so any page can use it.
window.SCHOOL_DATA = [
  { school: 'Ahmad Ibrahim Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Anchor Green Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Anderson Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Canberra Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Chongfu School', consultant: 'Martin', zone: 'North' },
  { school: 'Compassvale Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Edgefield Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Fernvale Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Fuchun Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Maris Stella High School (Pr)', consultant: 'Martin', zone: 'North' },
  { school: 'Marsiling Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Montfort Junior School', consultant: 'Martin', zone: 'North' },
  { school: 'Nan Chiau Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Northoaks Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'North Vista Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Northland Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Qihua Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Rivervale Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Sembawang Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Si Ling Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Woodgrove Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Xishan Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Yio Chu Kang Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Riverside Primary School', consultant: 'Martin', zone: 'North' },
  { school: 'Anderson Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Anderson Serangoon Junior College', consultant: 'Martin', zone: 'North' },
  { school: 'Bowen Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Canberra Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Christ Church Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Compassvale Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Edgefield Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Fuchun Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Hougang Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Maris Stella High School (Sec)', consultant: 'Martin', zone: 'North' },
  { school: 'Marsiling Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Montfort Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Nan Chiau High School', consultant: 'Martin', zone: 'North' },
  { school: 'North Vista Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Northbrooks Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Northland Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Pei Hwa Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Republic Polytechnic', consultant: 'Martin', zone: 'North' },
  { school: 'Riverside Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Sembawang Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Woodgrove Secondary School', consultant: 'Martin', zone: 'North' },
  { school: 'Fairfield Methodist School (Pr)', consultant: 'Martin', zone: 'South' },
  { school: 'Nan Hua High School', consultant: 'Martin', zone: 'West' },
  { school: 'Nan Hua Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'New Town Secondary School', consultant: 'Martin', zone: 'West' },
  { school: 'Ngee Ann Polytechnic', consultant: 'Martin', zone: 'West' },
  { school: 'NUS High School of Mathematics and Science', consultant: 'Martin', zone: 'West' },
  { school: 'Pei Hwa Presbyterian Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'Regent Secondary School', consultant: 'Martin', zone: 'West' },
  { school: 'School of Science and Technology', consultant: 'Martin', zone: 'West' },
  { school: 'Singapore Polytechnic', consultant: 'Martin', zone: 'West' },
  { school: 'West Grove Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'West View Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'Westwood Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'Yew Tee Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'Zhenghua Primary School', consultant: 'Martin', zone: 'West' },
  { school: 'Methodist Girls School (Sec)', consultant: 'Martin', zone: 'West' },
  { school: 'Zhenghua Secondary School', consultant: 'Martin', zone: 'West' },
  { school: 'Admirality Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Catholic High School (Pr)', consultant: 'Charlynn', zone: 'North' },
  { school: 'CHIJ St. Nicholas (Pr)', consultant: 'Charlynn', zone: 'North' },
  { school: 'Endeavour Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Evergreen Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Mee Toh School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Greendale Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Greenwood Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Horizon Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Hougang Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Huamin Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Innova Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Jiemin Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Naval Base Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'North Spring Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'North View Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Woodlands Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Woodlands Ring Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Xinmin Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Singapore Chinese Girls\' School (Pr)', consultant: 'Charlynn', zone: 'North' },
  { school: 'Palm View Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Peiying Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Yishun Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Rosyth School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Seng Kang Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Wellington Primary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Admiralty Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Catholic High School (Sec)', consultant: 'Charlynn', zone: 'North' },
  { school: 'CHIJ St. Joseph\'s Convent', consultant: 'Charlynn', zone: 'North' },
  { school: 'CHIJ St. Nicholas (Secondary)', consultant: 'Charlynn', zone: 'North' },
  { school: 'Chung Cheng High School (Yishun)', consultant: 'Charlynn', zone: 'North' },
  { school: 'Evergreen Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Yishun Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Woodlands Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Yishun Town Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Ahmad Ibrahim Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Naval Base Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Xinmin Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Orchid Park Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Punggol Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Seng Kang Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Serangoon Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Singapore Chinese Girls\' School (Independent)', consultant: 'Charlynn', zone: 'North' },
  { school: 'Singapore Sports School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Spectra Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Woodlands Ring Secondary School', consultant: 'Charlynn', zone: 'North' },
  { school: 'Yishun Innova Junior College', consultant: 'Charlynn', zone: 'North' },
  { school: 'Nanyang Polytechnic', consultant: 'Charlynn', zone: 'North' },
  { school: 'Pathlight (Sec)', consultant: 'Charlynn', zone: 'South' },
  { school: 'Pathlight (Pri)', consultant: 'Charlynn', zone: 'South' },
  { school: 'Jing Shan Pr', consultant: 'Charlynn', zone: 'South' },
  { school: 'Bedok Green Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Canossa Catholic Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Fengshan Primary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Meridian Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Ngee Ann Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Yu Neng Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Red Swastika Sch', consultant: 'Sapnaa', zone: 'East' },
  { school: 'St Anthony\'s Canossian Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Tampines North Pr', consultant: 'Sapnaa', zone: 'East' },
  { school: 'CHIJ Katong Pri', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Pasir Ris Pr *', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Junyuan Pr *', consultant: 'Sapnaa', zone: 'East' },
  { school: 'St Hilda\'s Primary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Temasek Primary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'White Sands Primary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Tao Nan School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Bedok Green Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'CHIJ Katong Convent', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Junyuan Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Manjusri Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Meridian Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Ngee Ann Sec', consultant: 'Sapnaa', zone: 'East' },
  { school: 'St. Anthony\'s Canossian Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'St. Patrick\'s School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Temasek JC', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Victoria JC', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Pasir Ris Sec *', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Temasek Polytechnic', consultant: 'Sapnaa', zone: 'East' },
  { school: 'St Hilda\'s Secondary School', consultant: 'Sapnaa', zone: 'East' },
  { school: 'Zhonghua Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Bendemeer Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Cedar Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'CHIJ (Toa Payoh) Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Farrer Park Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Gan Eng Seng School', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Hong Wen School', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Holy Innocents\' Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'River Valley Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'St Andrew\'s Junior School', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Yangzheng Pr', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Zhangde Primary School', consultant: 'Sapnaa', zone: 'South' },
  { school: 'St Joseph\'s Institution Junior', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Pei Chun Public (Sapnaa)', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Presbyterian High School', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Zhonghua Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Bartley Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Beatty Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Bendemeer Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Outram Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Fairfield Methodist School (Sec)', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Holy Innocents\' High', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Mayflower Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Nanyang JC', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Queenstown Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Peirce Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Peicai Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'St Andrew\'s JC', consultant: 'Sapnaa', zone: 'South' },
  { school: 'St Andrew\'s Secondary School ', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Serangoon Garden Sec', consultant: 'Sapnaa', zone: 'South' },
  { school: 'St Joseph\'s Institution', consultant: 'Sapnaa', zone: 'South' },
  { school: 'Chongzheng Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Damai Primary School', consultant: 'Krystle', zone: 'East' },
  { school: 'East View Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Angsana Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Haig Girls\' School', consultant: 'Krystle', zone: 'East' },
  { school: 'Paya Lebar Methodist Girls\' School (Pr)', consultant: 'Krystle', zone: 'East' },
  { school: 'Poi Ching School', consultant: 'Krystle', zone: 'East' },
  { school: 'St Stephen\'s Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Telok Kurau Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Northshore Primary School', consultant: 'Krystle', zone: 'East' },
  { school: 'Yumin primary', consultant: 'Krystle', zone: 'East' },
  { school: 'Gongshang Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Casuarina Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Maha Bodhi School', consultant: 'Krystle', zone: 'East' },
  { school: 'Fern Green Pri', consultant: 'Krystle', zone: 'East' },
  { school: 'Changkat Pr', consultant: 'Krystle', zone: 'East' },
  { school: 'Paya Lebar Methodist Girls\' School (Sec)', consultant: 'Krystle', zone: 'East' },
  { school: 'Victoria School', consultant: 'Krystle', zone: 'East' },
  { school: 'Anglican High', consultant: 'Krystle', zone: 'East' },
  { school: 'Cedar Girls’ Sec', consultant: 'Krystle', zone: 'East' },
  { school: 'Hai Sing Catholic', consultant: 'Krystle', zone: 'East' },
  { school: 'Chung Cheng High School (Main)', consultant: 'Krystle', zone: 'East' },
  { school: 'Damai Sec', consultant: 'Krystle', zone: 'East' },
  { school: 'ITE College East', consultant: 'Krystle', zone: 'East' },
  { school: 'East Spring Sec', consultant: 'Krystle', zone: 'East' },
  { school: 'Changkat Changi Sec', consultant: 'Krystle', zone: 'East' },
  { school: 'Loyang View Secondary School', consultant: 'Krystle', zone: 'East' },
  { school: 'Springfield Sec', consultant: 'Krystle', zone: 'East' },
  { school: 'Raffles Girls\' School', consultant: 'Krystle', zone: 'South' },
  { school: 'Raffles\' Instituition', consultant: 'Krystle', zone: 'South' },
  { school: 'St Margaret\'s Sec', consultant: 'Krystle', zone: 'South' },
  { school: 'Bukit Merah Sec', consultant: 'Krystle', zone: 'South' },
  { school: 'CHIJ St Theresa\'s Convent', consultant: 'Krystle', zone: 'South' },
  { school: 'School Of The Arts', consultant: 'Krystle', zone: 'South' },
  { school: 'Ang Mo Kio Sec', consultant: 'Krystle', zone: 'South' },
  { school: 'Crescent Girls\'', consultant: 'Krystle', zone: 'South' },
  { school: 'National JC', consultant: 'Krystle', zone: 'South' },
  { school: 'Kuo Chuan Presbyterian Sec', consultant: 'Krystle', zone: 'South' },
  { school: 'Catholic JC', consultant: 'Krystle', zone: 'South' },
  { school: 'CHIJ Our lady of good council (OLGC)', consultant: 'Krystle', zone: 'South' },
  { school: 'Fuhua Primary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Fuhua Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Greenridge Primary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Greenridge Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Henry Park Primary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Hua Yi Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Jurong Pioneer Junior College', consultant: 'Krystle', zone: 'West' },
  { school: 'Jurong Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Keming Primary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Kranji Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Anglo-Chinese Junior College', consultant: 'Sarah', zone: 'West' },
  { school: 'Assumption English Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Assumption Pathway School', consultant: 'Sarah', zone: 'West' },
  { school: 'Beacon Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Boon Lay Garden Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Boon Lay Secondary School', consultant: 'Krystle', zone: 'West' },
  { school: 'Bt Panjang Govt High School', consultant: 'Sarah', zone: 'West' },
  { school: 'Bukit Batok Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Bukit Panjang Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Bukit Timah Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Bukit View Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Bukit View Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'CHIJ Our Lady Queen of Peace', consultant: 'Sarah', zone: 'West' },
  { school: 'Chua Chu Kang Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Chua Chu Kang Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Clementi Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Clementi Town Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Commonwealth Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Concord Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Corporation Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Crest Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Dazhong Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'De La Salle School', consultant: 'Sarah', zone: 'West' },
  { school: 'Dunearn Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Frontier Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Hillgrove Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Hwa Chong Institution (High School and Junior College)', consultant: 'Sarah', zone: 'West' },
  { school: 'ITE West', consultant: 'Sarah', zone: 'West' },
  { school: 'Jurong Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Jurong West Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Jurong West Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Jurongville Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Juying Pioneer Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Juying Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Kranji Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Lakeside Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Lianhua Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Methodist Girls\' School (Primary)', consultant: 'Sarah', zone: 'West' },
  { school: 'Millennia Institute', consultant: 'Sarah', zone: 'West' },
  { school: 'Nanyang Girls\' High School', consultant: 'Sarah', zone: 'West' },
  { school: 'Nanyang Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Princess Elizabeth Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Qifa Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'River Valley High School', consultant: 'Sarah', zone: 'West' },
  { school: 'Rulang Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Shuqun Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'South View Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'St. Anthony\'s Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Swiss Cottage Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Teck Whye Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Unity Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Unity Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'West Spring Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'West Spring Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Westwood Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Xingnan Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Yuan Ching Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Yuhua Primary School', consultant: 'Sarah', zone: 'West' },
  { school: 'Yuhua Secondary School', consultant: 'Sarah', zone: 'West' },
  { school: 'East Spring Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Elias Park Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Geylang Methodist School (Pr)', consultant: 'Yuniza', zone: 'East' },
  { school: 'Opera Estate Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Park View Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Punggol Green Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Punggol View Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Sengkang Green Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tampines Pr', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tanjong Katong Pri', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tanjong Katong Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Waterway Primary', consultant: 'Yuniza', zone: 'East' },
  { school: 'Valour Primary School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Punggol Cove Primary School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Kong Hwa School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Springdale Primary School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Oasis Primary School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Bedok South Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Bedok View Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Dunman High', consultant: 'Yuniza', zone: 'East' },
  { school: 'Dunman Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Geylang Methodist School (Sec)', consultant: 'Yuniza', zone: 'East' },
  { school: 'Broadrick Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tampines Meridian JC', consultant: 'Yuniza', zone: 'East' },
  { school: 'Pasir Ris Crest Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tampines Secondary School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Tanjong Katong Girls School', consultant: 'Yuniza', zone: 'East' },
  { school: 'Yusof Ishak Sec', consultant: 'Yuniza', zone: 'East' },
  { school: 'Ai Tong School', consultant: 'Yuniza', zone: 'South' },
  { school: 'Alexandra Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Anglo Chinese Primary (Barker Rd)', consultant: 'Yuniza', zone: 'South' },
  { school: 'Anglo Chinese Junior', consultant: 'Yuniza', zone: 'South' },
  { school: 'Blangah Rise Pri', consultant: 'Yuniza', zone: 'South' },
  { school: 'Marymount Convent', consultant: 'Yuniza', zone: 'South' },
  { school: 'Kheng Cheng School', consultant: 'Yuniza', zone: 'South' },
  { school: 'New Town Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Queenstown Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Xinghua Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Pei Tong Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Punggol Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Radin Mas Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'St Gabriel\'s Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'St Margaret\'s Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Guangyang Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Mayflower Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'Gan Eng Seng Pr', consultant: 'Yuniza', zone: 'South' },
  { school: 'ACS (Independent)', consultant: 'Yuniza', zone: 'South' },
  { school: 'Anglo-Chinese (Barker Road) Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Yuying Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Kent Ridge Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Queensway Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'St Gabriel\'s Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Whitley Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'CHIJ Sec (Toa Payoh)', consultant: 'Yuniza', zone: 'South' },
  { school: 'Deyi Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Guangyang Sec', consultant: 'Yuniza', zone: 'South' },
  { school: 'Eunoia JC', consultant: 'Yuniza', zone: 'South' },
  { school: 'Yio Chu Kang Secondary School', consultant: 'Yuniza', zone: 'South' }
];
